apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: AzureDiskPVC
spec:
  storageClassName: Standard # Este debe llevar como "class name" el nombre del "Storage Class" que hayas creado, en este caso "Standard".
  # Como "Storage Class" no tiene configurado.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # No se configura nada en "selector" debido a que nos estamos conectando directamente con Azure.