apiVersion: v1
kind: Pod
metadata:
  name: MyPod
spec:
  containers:
    - name: MyFrontend
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: AzureDiskVolume
  volumes:
    - name: AzureDiskVolume
      persistentVolumeClaim:
        claimName: AzureDiskPVC
